### ISSUE TITLE
Error while Initializing Component

### ISSUE THREAD

**Issue by ztrglider** [kevinvincent/ha-wyzesense#101]
My sensors are all unavailable.  Restarted my HassIO running on RPi4 several times before I noticed the error message: 

> 2020-02-02 22:06:03 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform wyzesense
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform
>     await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
>   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
>     return fut.result()
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/wyzesense/binary_sensor.py", line 76, in setup_platform
>     _LOGGER.debug("Attempting to open connection to hub at " + config[CONF_DEVICE])
> TypeError: can only concatenate str (not "NoneType") to str

My config uses the "auto" option.

Here's my full log.
https://pastebin.com/h1Y25nLW

**Comment by jamescadd** [comment]
Did you resolve the issue?  I'm seeing the same problem with the "auto" option.

**Comment by ztrglider** [comment]
The issue has become intermittent. I completely uninstalled and reinstalled the component now it's a coin toss if it works or not after any given restart (though I suspect that it's because my hardware isn't powerful enough for how many components I'm running).

**Comment by jamescadd** [comment]
I'm still seeing this issue often, is there anything I can do to help debug?
