### ISSUE TITLE
Having the same issue right now, this behavior only started today after I updated the wyzsense integration to latest version (d4079eb) through HACS. Apparently the only thing that was changed was the readme file, so perhaps it's just a coincidence? Only other change to my setup made today was updating HACS itself to 13.0.

### ISSUE THREAD

**Issue by kevinvincent** [kevinvincent/ha-wyzesense#11]
Having the same issue right now, this behavior only started today after I updated the wyzsense integration to latest version (d4079eb) through HACS. Apparently the only thing that was changed was the readme file, so perhaps it's just a coincidence? Only other change to my setup made today was updating HACS itself to 13.0.

Here is some potential relevant info from my home-assistant.log file.

```
2019-08-11 22:47:24 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wyzesense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-08-11 22:47:29 ERROR (Thread-4) [wyzesense.gateway] Invalid packet: b'55aa531937a237373839423938394239383942394434020000016c839b'
2019-08-11 22:47:29 ERROR (Thread-4) [wyzesense.gateway] Mismatched checksum, remote=839B, local=065D
2019-08-11 22:47:39 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of platform wyzesense is taking over 10 seconds.
2019-08-11 22:47:39 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform wyzesense
  File "/config/custom_components/wyzesense/binary_sensor.py", line 76, in setup_platform
    ws = wyzesense.Open(config[CONF_DEVICE], on_event)
  File "/usr/local/lib/python3.7/site-packages/wyzesense/gateway.py", line 551, in Open
  File "/usr/local/lib/python3.7/site-packages/wyzesense/gateway.py", line 295, in __init__
  File "/usr/local/lib/python3.7/site-packages/wyzesense/gateway.py", line 484, in _Start
  File "/usr/local/lib/python3.7/site-packages/wyzesense/gateway.py", line 402, in _GetEnr
  File "/usr/local/lib/python3.7/site-packages/wyzesense/gateway.py", line 383, in _DoSimpleCommand
  File "/usr/local/lib/python3.7/site-packages/wyzesense/gateway.py", line 374, in _DoCommand
```

```
Sun Aug 11 2019 22:47:39 GMT-0400 (Eastern Daylight Time)
Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 149, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 76, in setup_platform
    ws = wyzesense.Open(config[CONF_DEVICE], on_event)
  File "/usr/local/lib/python3.7/site-packages/wyzesense/gateway.py", line 551, in Open
    return Dongle(device, event_handler)
  File "/usr/local/lib/python3.7/site-packages/wyzesense/gateway.py", line 295, in __init__
    self._Start()
  File "/usr/local/lib/python3.7/site-packages/wyzesense/gateway.py", line 484, in _Start
    self.ENR = self._GetEnr([0x30303030] * 4)
  File "/usr/local/lib/python3.7/site-packages/wyzesense/gateway.py", line 402, in _GetEnr
    resp = self._DoSimpleCommand(Packet.GetEnr(r_string))
  File "/usr/local/lib/python3.7/site-packages/wyzesense/gateway.py", line 383, in _DoSimpleCommand
    self._DoCommand(pkt, cmd_handler, timeout)
  File "/usr/local/lib/python3.7/site-packages/wyzesense/gateway.py", line 374, in _DoCommand
    raise TimeoutError("_DoCommand")
TimeoutError: _DoCommand
```

I am also on Hassio (HassOS 2.12 & Supervisor 173) / Home Assistant 0.97.1 on a Raspberry Pi 3B+.

_Originally posted by @SeanPM5 in https://github.com/kevinvincent/ha-wyzesense/issues/8#issuecomment-520288234_

**Comment by kevinvincent** [comment]
@SeanPM5 please update to the latest component code. The retrying changes are meant to retry when this exact failure occurs.

**Comment by SeanPM5** [comment]
I updated to it last night right after it was released, and have restarted several times since with no issues.

So far so good, seems to have improved reliability 👍

**Comment by kevinvincent** [comment]
That makes me really happy! Just to make sure, are you on a pi?

**Comment by SeanPM5** [comment]
Correct, I am on a Pi 3B+.

**Comment by kevinvincent** [comment]
Closing this out, feel free to reopen and/or comment below if it shows up again.
