### ISSUE TITLE
Added new Wyze Sense after 1.07 upgrade and sensor not updating status

### ISSUE THREAD

**Issue by DesertDwellerEv** [kevinvincent/ha-wyzesense#116]
Looking at the log for that sensor:
Log Details (ERROR)
Logger: homeassistant.helpers.entity
Source: helpers/template.py:221
First occurred: 2:39:36 PM (1 occurrences)
Last logged: 2:39:36 PM

Update for sensor.rear_sliding_door_signal fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/template/sensor.py", line 224, in async_update
    self._state = self._template.async_render()
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 221, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by DesertDwellerEv** [comment]
After reboot, sensor appears and has valid states.
