### ISSUE TITLE
Permission denied 'dev/hidraw0'

### ISSUE THREAD

**Issue by nukefrenzy** [kevinvincent/ha-wyzesense#15]
I'm running Hassbian on an RPi 3b+.  I installed everything through HACS and get an amber light.  I verified the USB device is on hidraw0.  I get the following errors on startup.

> 2019-08-16 15:23:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-08-16 15:23:17 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wyzesense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-08-16 15:23:21 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 149, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/wyzesense/binary_sensor.py", line 81, in setup_platform
    ws = beginConn()
  File "</srv/homeassistant/lib/python3.7/site-packages/decorator.py:decorator-gen-2>", line 2, in beginConn
  File "/srv/homeassistant/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/srv/homeassistant/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/homeassistant/.homeassistant/custom_components/wyzesense/binary_sensor.py", line 79, in beginConn
    return wyzesense.Open(config[CONF_DEVICE], on_event)
  File "/srv/homeassistant/lib/python3.7/site-packages/wyzesense/gateway.py", line 551, in Open
    return Dongle(device, event_handler)
  File "/srv/homeassistant/lib/python3.7/site-packages/wyzesense/gateway.py", line 283, in __init__
    self.__fd = os.open(device, os.O_RDWR | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/hidraw0'

**Comment by kevinvincent** [comment]
Please follow the troubleshooting instructions for this error in the readme (towards the bottom). If once you've tried that it doesnt work let me know!

**Comment by nukefrenzy** [comment]
I just saw this on a HA forum post.  I must have missed it on the readme page.  This worked for me and everything is good now.  Thanks for your help and for making these great cheap sensors work with HA!

**Comment by kevinvincent** [comment]
No worries! I'm glad it's working well for you!
