### ISSUE TITLE
HA WyzeSense stopped working

### ISSUE THREAD

**Issue by DesertDwellerEv** [kevinvincent/ha-wyzesense#153]
Update to latest Home Assistant 0.111.4 and get the following:
Log Details (ERROR)
Logger: custom_components.wyzesense.wyzesense_custom
Source: helpers/entity.py:426
Integration: wyzesense (documentation)
First occurred: June 23, 2020, 7:44:58 AM (1 occurrences)
Last logged: June 23, 2020, 7:44:58 AM

Ignoring non-OSError in worker thread. Please share the error logs with the developers.
Traceback (most recent call last):
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 371, in _Worker
    self._HandlePacket(pkt)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 344, in _HandlePacket
    handler(pkt)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 269, in _OnSensorAlarm
    self.__on_event(self, e)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 110, in on_event
    entities[event.MAC].schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 426, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'

**Comment by VarenDerpsAround** [comment]
```
self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
```

Interesting, mine won't reinstall after a failure, enabling logs now. I'll compare to mine.

**Comment by sasanasit** [comment]
I’m getting the same error

**Comment by desertblade** [comment]
I am getting a similar error on 0.112 on startup

  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 416, in schedule_update_ha_state
    assert self.hass is not None

Believe its due to the new faster loading the components are not ready.

Here is a work around:
1. Wait till Home Assistant is fully loaded
2. Goto Developer Tools->Services
3. Call wyzesense.scan 

Sensors are now reporting. Probably need to add a delay on startup or something.

**Comment by seayworld** [comment]
Your work around did the trick.  After a scan all devices resumed reporting.

Hopefully an easy fix in the initialization code.

**Comment by DesertDwellerEv** [comment]
Clean restart.
Waited for UI to catch up.
Ran Wyze Scan service
Still not working.
Do I have to put Wyze sensors in pairing mode?

**Comment by desertblade** [comment]
Maybe you have a different issue. I did not have to repair the devices, kicking off the scan restarted the service. When I fired off the rescan my home assistant was up for at least 30 minutes.

**Comment by DesertDwellerEv** [comment]
Bounced it one more time.
Scan again.
Then activated each sensor.
They're now working.
Thanks

**Comment by desertblade** [comment]
I have had 2 upgrades (currently 0.112.3) and 1 restart, each time the WYZE sensors are working fine.

**Comment by DesertDwellerEv** [comment]
Yeah, seems to be working fine now.
