### ISSUE TITLE
devices and services gone after upgrading to 0.116.2

### ISSUE THREAD

**Issue by matthewj301** [kevinvincent/ha-wyzesense#186]
My configured Contact Sensors and Motion Sensors became unavailable, and all wyzesense services disappeared after upgrading to 0.116.2. Seems like the dictionary/key config[CONF_DEVICE] was changed in some way with the following error.

Error in HA logs:

2020-10-11 11:53:26 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up wyzesense platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 78, in setup_platform
    _LOGGER.debug("Attempting to open connection to hub at " + config[CONF_DEVICE])
TypeError: can only concatenate str (not "NoneType") to str

**Comment by matthewj301** [comment]
Sorry, this was my mistake. I switched hardware for HA and forgot to move the hub dongle.
