### ISSUE TITLE
Error while setting up wyzesense platform for binary_sensor

### ISSUE THREAD

**Issue by truepaint** [kevinvincent/ha-wyzesense#200]
Went through the install many times and still can get this working, I have tried 3 wyze hub device. this is my LOG and wyzesense.scan is not showing up,I am on a VM

2021-01-07 16:33:13 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-07 16:33:16 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wyzesense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-07 16:33:17 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up wyzesense platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 78, in setup_platform
    _LOGGER.debug("Attempting to open connection to hub at " + config[CONF_DEVICE])
TypeError: can only concatenate str (not "NoneType") to str

**Comment by stanwebber** [comment]
sounds like a duplicate of issue #189.

**Comment by IIAIronWolf** [comment]
This git is no longer being maintained.
