### ISSUE TITLE
Error after recent update / no sensor status

### ISSUE THREAD

**Issue by sockmonkey0223** [kevinvincent/ha-wyzesense#228]
I don't know if this integration is still maintained, but I'm taking the chance in case someone can help.

Yesterday I went from 2022.07.06 --> 2022.07.07 and also installed the latest OS (8.4).
Since then, I receive the following error on startup and none of my sensors will update their status:

Logger: custom_components.wyzesense.wyzesense_custom
Source: helpers/entity.py:660
Integration: wyzesense ([documentation](https://github.com/kevinvincent/wyzesense))
First occurred: 7:08:37 PM (1 occurrences)
Last logged: 7:08:37 PM

Ignoring non-OSError in worker thread. Please share the error logs with the developers.
Traceback (most recent call last):
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 374, in _Worker
    self._HandlePacket(pkt)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 347, in _HandlePacket
    handler(pkt)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 272, in _OnSensorAlarm
    self.__on_event(self, e)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 110, in on_event
    entities[event.MAC].schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 660, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'

**Comment by randomsnack** [comment]
My sensor also stop working recently, I tried removing it (wyzesense.remove) and re-adding it (wyzesense.scan). It will recognize it, but doesn't have a MAC address. Without a MAC address it will not work, you can test if you have the same problem.

error: Sensor found and added as: binary_sensor.wyzesense_ (unless you have customized the entity ID prior).
To add more sensors, call wyzesense.scan again.
