### ISSUE TITLE
No such file or directory: '/dev/hidraw1'

### ISSUE THREAD

**Issue by smnino** [kevinvincent/ha-wyzesense#34]
This is probably an environment issue but, I'm a spray and pray Linux user that has very little idea what he's doing so... hope you have the patience to help me. 

Hassbian 97.3 running in a docker on an older apple laptop
Wyze Sense Component version 0.0.5
The wyze hub us plugged directly into a USB port on the laptop
The light is amber, has never been blue

I think this may be related to permissions but, only because the log reports "FileNotFoundError: [Errno 2] No such file or directory: '/dev/hidraw1'"

I have created `/etc/udev/rules.d/99-com.rules` and I tried with `KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="homeassistant"` and then 
`KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="root"` as I'm not sure what user the HA is running under the docker as. I think its running as root (I know, I know) but, I'm not certain.

Output from dmesg | grep hidraw: 

[    3.320316] hidraw: raw HID events driver (C) Jiri Kosina
[    3.388284] appleir 0003:05AC:8242.0001: input,hiddev0,hidraw0: USB HID v1.11 Device [Apple Computer, Inc. IR Receiver] on usb-0000:00:04.0-5/input0
[    3.880413] hid-generic 0003:1A86:E024.0002: hiddev1,hidraw1: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:06.0-2/input0
[    4.176254] apple 0003:05AC:0236.0003: input,hidraw2: USB HID v1.11 Keyboard [Apple, Inc. Apple Internal Keyboard / Trackpad] on usb-0000:00:04.0-6/input0
[    4.176729] apple 0003:05AC:0236.0004: hidraw3: USB HID v1.11 Device [Apple, Inc. Apple Internal Keyboard / Trackpad] on usb-0000:00:04.0-6/input1

Log reads:

2019-09-17 21:18:05 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 149, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 82, in setup_platform
    ws = beginConn()
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-2>", line 2, in beginConn
  File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/config/custom_components/wyzesense/binary_sensor.py", line 80, in beginConn
    return Open(config[CONF_DEVICE], on_event)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 561, in Open
    return Dongle(device, event_handler)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 285, in __init__
    self.__fd = os.open(device, os.O_RDWR | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/hidraw1'

**Comment by smnino** [comment]
I needed to connect the docker to the hidraw. I did so by adding the following entry in my docker-compose file:

    devices:
      - /dev/hidraw1:/dev/hidraw1

**Comment by kevinvincent** [comment]
Sorry I wasn't able to get to this sooner, Im glad you found the issue. Theres also a new update via HACS that should auto detect the hidraw device so you don't need it harcoded in your config file.
