### ISSUE TITLE
FileNotFound Error - HASS.IO

### ISSUE THREAD

**Issue by seanemclean** [kevinvincent/ha-wyzesense#37]
I'll preface this by saying I barely know what I'm doing with this stuff, but I get by. I got Wyzesense up and running just fine yesterday, sensors put into automations in node red and working normally - this morning, all are now in 'entity not found' status. Removed wyzesense from customcomponents, rebooted them, added them back in and was working fine all day, just stopped working again (no other changes).  Error log is below. Any thoughts? I'm loving this integration, but not sure what I need to do to stabilize it.

Running HASSIO .99.2 and current wyzesense on an ubuntu VM on a Windows PC, usb receiver plugged directly into PC.

`Wed Sep 25 2019 20:31:51 GMT-0400 (Eastern Daylight Time)
Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 82, in setup_platform
    ws = beginConn()
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-2>", line 2, in beginConn
  File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/config/custom_components/wyzesense/binary_sensor.py", line 80, in beginConn
    return Open(config[CONF_DEVICE], on_event)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 561, in Open
    return Dongle(device, event_handler)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 285, in __init__
    self.__fd = os.open(device, os.O_RDWR | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/hidraw1'`

Sensor light is still blue which is weird.

**Comment by seanemclean** [comment]
Update, although initially configured and functioning on hidraw1, I switched to hidraw0 and it failed, tried hidraw2 and its functioning normally again.

Not sure how long it will stay stable, but does anyone know how to lock a device to a particular hidraw in this type of environment? If you could explain it like I'm a five year old, I'd really appreciate it.

**Comment by WayneManion** [comment]
I made [a pull request](https://github.com/kevinvincent/ha-wyzesense/pull/44) that automatically finds the correct hidraw device to use.

**Comment by kevinvincent** [comment]
@WayneManion's pull request is now pulled in. Please update via HACS and remote the device field from your config.

**Comment by seanemclean** [comment]
@kevinvincent 

Hi Kevin - my install is not via HACS but through direct install. I just re-installed using the repository, but now I'm getting this error:

Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 59, in setup_platform
    _LOGGER.debug("Attempting to open connection to hub at " + config[CONF_DEVICE])
TypeError: can only concatenate str (not "NoneType") to str

**Comment by kevinvincent** [comment]
Hmm can you post the full file you have installed?

**Comment by kevinvincent** [comment]
Also try setting the device to "auto"
