### ISSUE TITLE
Trying to pair new sensors but I don't have the scan service listed

### ISSUE THREAD

**Issue by jimtino** [kevinvincent/ha-wyzesense#47]
Thank you for creating this integration. I was able to successfuly pair and use one sensor. I'm now trying to add another but do not see the scan service available.

Raspberry PI4 running latest version of hassio.

`tried` enabling logs and I'm getting this error on start up:

Log Details (ERROR)
Mon Oct 21 2019 22:47:43 GMT-0400 (Eastern Daylight Time)
Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 85, in setup_platform
    result = ws.List()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 507, in List
    sensors = self._GetSensors()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 479, in _GetSensors
    self._DoCommand(Packet.GetSensorList(count), cmd_handler, timeout=self._CMD_TIMEOUT * count)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 384, in _DoCommand
    raise TimeoutError("_DoCommand")
TimeoutError: _DoCommand

**Comment by eps000** [comment]
Any luck with this? I am having the same issue.

**Comment by mattyb8562** [comment]
Take a look at TimeoutError: _DoCommand #27 issue. It's the same thing you are describing. I believe they have a workaround to add sensors.
