### ISSUE TITLE
voluptuous.error.MultipleInvalid: string value is None for dictionary value @ data['mac']

### ISSUE THREAD

**Issue by biga888** [kevinvincent/ha-wyzesense#52]
Log Details (ERROR)
Wed Nov 06 2019 08:07:26 GMT-0800 (Pacific Standard Time)
string value is None for dictionary value @ data['mac']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1214, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: string value is None for dictionary value @ data['mac']

I was getting this error when trying to remove a door sensor. I could add and remove other sensors, but this one would always give me this error. I was able to get it to a point that HA did not know what it was and just had a state. I did some searching and found that I needed to enclose the mac address in quotes. All the others had no problem, but this one must of had some corruption in the name? 
I was also thinking because it was the last one in the list of sensors I had? 

mac: "777EXXX"

I am going to do some more testing tonight to see if I can re add and remove without the quotes.

**Comment by biga888** [comment]
I tried adding and removing all my components and only this one requires quotes. Seems like the problem is with HA itself and not this plugin. Would be good to leave here just in case someone else has this issue.

I also checked the entity file that lists all the found sensors and it is the same as the rest, so not sure what the issue is.
