### ISSUE TITLE
Getting a TypeError after attempting to add the binary sensor

### ISSUE THREAD

**Issue by Bottleface** [kevinvincent/ha-wyzesense#64]
I installed via HACS and restarted, everything seemed fine.  I added the binary sensor to my configuration.yaml file exactly as below.

![image](https://user-images.githubusercontent.com/9113058/69485166-f57ecd80-0df8-11ea-899f-2c26d892eeb1.png)

Once I checked my config for errors the logs spit out the following error and I'm not sure what exactly needs to be done.

> 2019-11-23 13:25:01 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 40, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 136, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 122, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/core.py", line 29, in post
    errors = await async_check_ha_config_file(request.app["hass"])
  File "/usr/src/homeassistant/homeassistant/config.py", line 795, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 154, in async_check_ha_config_file
    hass, p_name
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 48, in async_get_integration_with_requirements
    hass, integration.domain, integration.requirements
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 77, in async_process_requirements
    if pkg_util.is_installed(req):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 45, in is_installed
    return version(req.project_name) in req
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3137, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 703, in contains
    item = parse(item)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 31, in parse
    return Version(version)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

I'm running hass.io within hassos and have the latest version of HACS installed.  I've uninstalled and reinstalled this component a few times, both manually and via HACS.  At one point the error stated that it couldn't find the module "retry".  After reinstalling that error went away and the below error popped up.  I'm wondering if this is just a more cryptic error for some issue with the retry module.

**Comment by Bottleface** [comment]
Fixed it, should have just stuck with it a few more minutes.  I'm not entirely sure what was wrong, though I still suspect something wrong with the "reply" module.  To fix all I had to do was rebuild my home assistant.  If you're running HASSOS just hit enter, then enter the default user "root".  Then you can issue the command:
`ha rebuild`

After it finished it restarted my home assistant instance and I was able to use the component.
