### ISSUE TITLE
Permission denied error on NUC

### ISSUE THREAD

**Issue by arsaboo** [kevinvincent/ha-wyzesense#71]
I am getting the following error:
```bash
2019-12-05 11:09:13 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/wyzesense/binary_sensor.py", line 91, in setup_platform
    ws = beginConn()
  File "<decorator-gen-2>", line 2, in beginConn
  File "/srv/homeassistant/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/srv/homeassistant/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/homeassistant/.homeassistant/custom_components/wyzesense/binary_sensor.py", line 89, in beginConn
    return Open(config[CONF_DEVICE], on_event)
  File "/home/homeassistant/.homeassistant/custom_components/wyzesense/wyzesense_custom.py", line 561, in Open
    return Dongle(device, event_handler)
  File "/home/homeassistant/.homeassistant/custom_components/wyzesense/wyzesense_custom.py", line 285, in __init__
    self.__fd = os.open(device, os.O_RDWR | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/hidraw0'
```

I have already created the 99-com.rules file as indicated in https://github.com/kevinvincent/ha-wyzesense#troubleshooting

```
arsaboo@aloknuc:~$ dmesg | grep hidraw
[    1.964543] hidraw: raw HID events driver (C) Jiri Kosina
[    1.967062] hid-generic 0003:1A86:E024.0001: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
```

**Comment by JFC-Dev** [comment]
I also have this issue with one of my sensors, I don't know how to completely reset it. I think it might be stored in the Wyze sensor bridge

**Comment by arsaboo** [comment]
@kevinvincent Any thoughts? The dongle stays amber throughout.

**Comment by kevinvincent** [comment]
The device in your `dmesg | grep hidraw` is mounted to hidraw0 instead of hidraw1.

The hidraw device number may change across restarts, please update to the latest version of this custom_component and set the device to "auto" in your config.

**Comment by kevinvincent** [comment]
Try setting the udev file rule to
`KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0666"`

**Comment by arsaboo** [comment]
`MODE="0666"` works 🎉 

Thanks @kevinvincent
