### ISSUE TITLE
Receiver intermittently stops working

### ISSUE THREAD

**Issue by X-Light** [kevinvincent/ha-wyzesense#73]
Hi,

Since several weeks I am experiencing intermittent stop for my sensors. 
With version 0.0.4, my receiver suddenly stop working until home assistant restart. I have not noticed anything strange in the logs, except the wrong timestamp when the receiver stop working

0.0.4 Working

> 2019-12-12 20:19:40 INFO (Thread-2) [custom_components.wyzesense.wyzesense_custom] LOG: time=2019-12-12T20:19:34.156000, data=b'a2373738353237453202010b3f'
> 2019-12-12 20:19:40 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa531d190000016efb566792a237373835323745320216650001010b3f5407bb55aa531d190000016efb566792a237373835323745320216650001010b3f5407bb'
> 2019-12-12 20:19:40 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa531d190000016efb566792a237373835323745320216650001010b3f5407bb'
> 2019-12-12 20:19:40 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=5319, Payload=b'0000016efb566792a237373835323745320216650001010b3f54'
> 2019-12-12 20:19:40 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=53FF, Payload=ACK(5319)
> 2019-12-12 20:19:40 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa555319ff026a'
> 2019-12-12 20:19:40 DEBUG (Thread-2) [custom_components.wyzesense.binary_sensor] {'available': True, 'mac': '778527E2', 'state': 1, 'device_class': 'motion', 'timestamp': '2019-12-12T20:19:34.162000', 'rssi': -84, 'battery_level': 101}
> 2019-12-12 20:19:40 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa531d190000016efb566792a237373835323745320216650001010b3f5407bb'
> 2019-12-12 20:19:40 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa531d190000016efb566792a237373835323745320216650001010b3f5407bb'
> 2019-12-12 20:19:40 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=5319, Payload=b'0000016efb566792a237373835323745320216650001010b3f54'
> 2019-12-12 20:19:40 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=53FF, Payload=ACK(5319)
> 2019-12-12 20:19:40 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa555319ff026a'

----------------------------------------------------------------------------------------------------------------------------

0.0.4 Not working

> 2019-12-12 21:22:56 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa53193500000000000000000ea2373738353237453202000b44045c'
> 2019-12-12 21:22:56 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=5335, Payload=b'00000000000000000ea2373738353237453202000b44'
> 2019-12-12 21:22:56 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=53FF, Payload=ACK(5335)
> 2019-12-12 21:22:56 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa555335ff0286'
> 2019-12-12 21:22:56 INFO (Thread-2) [custom_components.wyzesense.wyzesense_custom] LOG: time=1970-01-01T02:00:00, data=b'a2373738353237453202000b44'
> 2019-12-12 21:22:56 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa53193500000000000000000ea2373738353237453203010b45045e55aa53193500000000000000000ea2373738353237453202000b46045e55aa53193500000000000000000ea2373738353237453202010b43045c55aa53193500000000000000000ea2373738353237453202000b44045c00016efb566792a237'
> 2019-12-12 21:22:56 ERROR (Thread-2) [custom_components.wyzesense.wyzesense_custom] Invalid packet: b'55aa53193500000000000000000ea2373738353237453203010b45045e'
> 2019-12-12 21:22:56 ERROR (Thread-2) [custom_components.wyzesense.wyzesense_custom] Mismatched checksum, remote=045E, local=045F
----------------------------------------------------------------------------------------------------------------------------

0.0.7 Timeout during scan

> 2019-12-17 20:26:11 DEBUG (SyncWorker_4) [custom_components.wyzesense.wyzesense_custom] Start Scan...
> 2019-12-17 20:26:11 DEBUG (SyncWorker_4) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=531C, Payload=b'01'
> 2019-12-17 20:26:11 DEBUG (SyncWorker_4) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa5553041c010173'
> 2019-12-17 20:26:16 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1580722992] _DoCommand
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
>     connection.context(msg),
>   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1235, in async_call
>     await asyncio.shield(self._execute_service(handler, service_call))
>   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1262, in _execute_service
>     await self._hass.async_add_executor_job(handler.func, service_call)
>   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/home/homeassistant/.homeassistant/custom_components/wyzesense/binary_sensor.py", line 140, in on_scan
>     result = ws.Scan()
>   File "/home/homeassistant/.homeassistant/custom_components/wyzesense/wyzesense_custom.py", line 530, in Scan
>     self._DoSimpleCommand(Packet.EnableScan())
>   File "/home/homeassistant/.homeassistant/custom_components/wyzesense/wyzesense_custom.py", line 393, in _DoSimpleCommand
>     self._DoCommand(pkt, cmd_handler, timeout)
>   File "/home/homeassistant/.homeassistant/custom_components/wyzesense/wyzesense_custom.py", line 384, in _DoCommand
>     raise TimeoutError("_DoCommand")
> TimeoutError: _DoCommand

After 0.0.4, I updated to 0.0.6 and home assistant to 0.103.0, but the behaviour was the same - The sensor light in blue until it stop working, then it start to light in yellow, or alternate between blue and yewllow light. 

My setup - Home Assistant on RPI running Hassbian. 2 sensors (1 motion and 1 door) + 1 receiver on the same RPI. I tried to stop each sensor, but the received was not fixed, so I am excluding the battery issue. I expected to fix the issue with 0.0.7, but the Scan always times out. 

I uploaded some logs here:
0.0.4 - https://pastebin.com/1GQuQbYW
0.0.7 - https://pastebin.com/XvcAiWTN

Please suggest what to do next, as I ran out of ideas. 

Thanks!

**Comment by X-Light** [comment]
The reason - low battery in one of the sensors. The sensor itself reported the battery at ~80%.
