### ISSUE TITLE
Wyze integration is suddenly not working as it should.

### ISSUE THREAD

**Issue by rclifton70** [kevinvincent/ha-wyzesense#75]
I've been using the wyze integration for several months now without issue and it has been great!  Suddenly, sometime within the last week something has changed and I'm not sure exactly when, why or how.
 
I have Hass.io installed on an i3 NUC with 16GB of ram and a 120GB SSD.  This has worked flawlessly until yesterday when I noticed after a reboot that all my wyze sensors show as "Entity not available:" if I manual open/close the door or window or walk in front of the motion sensor they start reporting accurately.  The receiver has a blue light but I notice that I no longer have any wyze services available within developer tools and nothing shows up for wyze in the integrations tab.

I have tried uninstalling/reinstalling the integration with the same results, I wiped my setup and restored from a snapshot from a few weeks ago and same result, I am at a loss as to what to do next.  I enabled the logging in my config file and I see the following with regards to the wyze integration but have no idea what exactly it is complaining about:

2019-12-20 11:21:25 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of platform wyzesense is taking over 10 seconds.
2019-12-20 11:21:41 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 94, in setup_platform
    result = ws.List()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 507, in List
    sensors = self._GetSensors()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 479, in _GetSensors
    self._DoCommand(Packet.GetSensorList(count), cmd_handler, timeout=self._CMD_TIMEOUT * count)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 384, in _DoCommand
    raise TimeoutError("_DoCommand")
TimeoutError: _DoCommand

Any help would be appreciated, Thanks!!

**Comment by rclifton70** [comment]
Sorry, I should have looked a bit more.  After continuing to read through numerous posts, I found someone here who was having a somewhat similar problem.  Upon further investigation I found a dead window sensor.  After resetting the hub, deleting that entity from within home assistant, and then repairing all of my other sensors the integration is working 100% normally again..
