### ISSUE TITLE
Error in hass 0.103.3

### ISSUE THREAD

**Issue by erlanger** [kevinvincent/ha-wyzesense#76]
I am getting the following error after restarting hass:

```
Dec 22 04:58:56 nonie hass[1992]: Traceback (most recent call last):
Dec 22 04:58:56 nonie hass[1992]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Dec 22 04:58:56 nonie hass[1992]:     self.run()
Dec 22 04:58:56 nonie hass[1992]:   File "/usr/lib/python3.8/threading.py", line 870, in run
Dec 22 04:58:56 nonie hass[1992]:     self._target(*self._args, **self._kwargs)
Dec 22 04:58:56 nonie hass[1992]:   File "/var/lib/hass/custom_components/wyzesense/wyzesense_custom.py", line 371, in _Worker
Dec 22 04:58:56 nonie hass[1992]:     self._HandlePacket(pkt)
Dec 22 04:58:56 nonie hass[1992]:   File "/var/lib/hass/custom_components/wyzesense/wyzesense_custom.py", line 344, in _HandlePacket
Dec 22 04:58:56 nonie hass[1992]:     handler(pkt)
Dec 22 04:58:56 nonie hass[1992]:   File "/var/lib/hass/custom_components/wyzesense/wyzesense_custom.py", line 269, in _OnSensorAlarm
Dec 22 04:58:56 nonie hass[1992]:     self.__on_event(self, e)
Dec 22 04:58:56 nonie hass[1992]:   File "/var/lib/hass/custom_components/wyzesense/binary_sensor.py", line 92, in on_event
Dec 22 04:58:56 nonie hass[1992]:     entities[event.MAC].schedule_update_ha_state()
Dec 22 04:58:56 nonie hass[1992]:   File "/usr/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 418, in schedule_update_ha_state
Dec 22 04:58:56 nonie hass[1992]:     self.hass.add_job(self.async_update_ha_state(force_refresh))
Dec 22 04:58:56 nonie hass[1992]: AttributeError: 'NoneType' object has no attribute 'add_job'
```

The error clears when I force a movement on the motion sensor.

**Comment by declanshanaghy** [comment]
Same here. Was working fine for 2 days since upgrade but suddenly failing.
