### ISSUE TITLE
_DoCommand in 0.0.6

### ISSUE THREAD

**Issue by Colgaton** [kevinvincent/ha-wyzesense#83]
Brand new install of HA, running Hassios inside a vm in proxmox.

Device is there:

 docker exec 21e425c1a3e2 ls -l /dev/hi*
crw-------    1 root     root      244,   0 Jan  6 05:11 /dev/hidraw0

configuration.yaml:
binary_sensor:
  - platform: ring
  - platform: wyzesense
    device: "/dev/hidraw0"

From log file:

2020-01-06 05:11:46 DEBUG (SyncWorker_8) [custom_components.wyzesense.binary_sensor] WYZESENSE v0.0.4
2020-01-06 05:11:46 DEBUG (SyncWorker_8) [custom_components.wyzesense.binary_sensor] Attempting to open connection to hub at /dev/hidraw0
2020-01-06 05:11:47 DEBUG (SyncWorker_8) [custom_components.wyzesense.wyzesense_custom] Start Inquiry...
2020-01-06 05:11:47 DEBUG (SyncWorker_8) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=4327, Payload=<None>
2020-01-06 05:11:47 DEBUG (SyncWorker_8) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa55430327016c'
2020-01-06 05:11:57 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 91, in setup_platform
    ws = beginConn()
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-2>", line 2, in beginConn
  File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/config/custom_components/wyzesense/binary_sensor.py", line 89, in beginConn
    return Open(config[CONF_DEVICE], on_event)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 561, in Open
    return Dongle(device, event_handler)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 297, in __init__
    self._Start()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 492, in _Start
    self._Inquiry()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 398, in _Inquiry
    resp = self._DoSimpleCommand(Packet.Inquiry())
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 393, in _DoSimpleCommand
    self._DoCommand(pkt, cmd_handler, timeout)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 379, in _DoCommand
    self._SendPacket(pkt)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 331, in _SendPacket
    pkt.Send(self.__fd)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 106, in Send
    ss = os.write(fd, pkt)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by Colgaton** [comment]
Funny thing was it worked for a few, I was setting up HA (moving config from an old install) and after restarting it a few times it stopped working.

**Comment by Colgaton** [comment]
Nevermind, the device name changed for some weird reason. After pointing to /dev/hidraw1 it started working again.
