### ISSUE TITLE
Wyze Sense sensors stopped working

### ISSUE THREAD

**Issue by damato300x7** [kevinvincent/ha-wyzesense#84]
I woke up today and none of my sensors are working.  Here is a link to my log.

https://pastebin.com/uvvGftVJ

Hope someone can help.

**Comment by bseishen** [comment]
Same issue, I *think* my home assistant docker was updated that broke this.
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 94, in setup_platform
    result = ws.List()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 507, in List
    sensors = self._GetSensors()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 479, in _GetSensors
    self._DoCommand(Packet.GetSensorList(count), cmd_handler, timeout=self._CMD_TIMEOUT * count)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 384, in _DoCommand
    raise TimeoutError("_DoCommand")
TimeoutError: _DoCommand`

**Comment by damato300x7** [comment]
i uninstalled wyze sense component and all is well again.  Although I had to go around and reset each sensor.  But it is working again.

**Comment by papacrown** [comment]
Getting the same issue, I have lots of sensors so I'm going to hold out for a fix on this before having to go around and reseting them.

**Comment by jthomasdewald** [comment]
+1 

A restart of HA worked for me, but this is the third time in two days this has occurred. Not finding much useful in my logs though.

**Comment by damato300x7** [comment]
Mine just quit working again.

**Comment by Pelphry17** [comment]
My sensors seem to stop reporting after roughly a day or so of working fine. A restart of the Homeassistant server fixes it every time. No need to re-add them just a reboot and they will report fine. I am running HassIO in a Virtual Box machine. Will keep checking logs for any issues I can find.

**Comment by kevinvincent** [comment]
Can all of you please try updating to version `0.0.7`. Please make sure to follow the update instructions where you must retrigger each sensor once updating the component for the sensor to show up in Home Assistant. After you do that it should solve the error that @bseishen posted above.

**Comment by badrobit** [comment]
@kevinvincent could you explain what you mean by "retrigger"? Thanks!

**Comment by photinus** [comment]
If you go and open each door/window/contact sensor and trigger each motion
sensor, that is what is intended. They will show up as missing entities
until you do thay

**Comment by Pelphry17** [comment]
Mine have been solid since the update. Thank You.

**Comment by broyuken** [comment]
Mine have been worse since the update. Not sure if it was this update or updating HA, but I have to uninstall/reinstall this addon then restart HA to get them back.

**Comment by peterpme** [comment]
I recently started having this issue soon. For what it's worth, I didn't update for awhile. Thanks for your help!

**Comment by damato300x7** [comment]
The last time I had this issue I switched to the master instead of the .6 or .7 and I have had 0 issues in 12 days.  I dont know the difference between the versions but no issues so far so I am going to leave it as is for now.

**Comment by kevinvincent** [comment]
@damato300x7 master is actually now the same as 0.0.7 (it was ahead of 0.0.6 a couple of weeks ago).

**Comment by javand** [comment]
I also have this issue...I been on 0.0.7, I would uninstall then reinstall - retrigger all the sensors and everything would be working fine for a day or two then....nothing. The sensors will just stop working.

**Comment by photinus** [comment]
@javand Can you put your logs for the wyze component into debug and share a full run from start to not working?

**Comment by javand** [comment]
> @javand Can you put your logs for the wyze component into debug and share a full run from start to not working?

Sure but it may take a few days. I just restarted HA and afterwards all the sensors started working again. Duplicating the issue seems to take a few days - I'll turn on debug again and attach them.

**Comment by kevinvincent** [comment]
@javand Whenever the issue appears again can you also ssh into the box and run `dmesg` and post the output as well? It will let us see if theres any issues going on with usb disconnects and reconnects (which this component does not handle at all and is the next area of improvement).

**Comment by javand** [comment]
> @javand Whenever the issue appears again can you also ssh into the box and run `dmesg` and post the output as well? It will let us see if theres any issues going on with usb disconnects and reconnects (which this component does not handle at all and is the next area of improvement).

Will do

**Comment by biga888** [comment]
Hi Kevin, I am having the same symptoms. Do you want the dmesg from the host machine or HA?

**Comment by javand** [comment]
As promised @kevinvincent @photinus 

Took a few lines out the ha log to get under the pastebin limit but as you can see - the sensors stop working sometime on 1/31. 

ha log:  https://pastebin.com/KsTUjP8u
dmesg log: https://pastebin.com/UeiFNYUz

**Comment by javand** [comment]
I think my issue could be related to this: https://github.com/home-assistant/home-assistant/issues/21291 . Took a look at my latest logs from `dmesg` and noticed a usb disconnect. Not sure if this is a bug related to the Ubuntu kernel I'm running but going to attempt to update to the latest patch.

**Comment by yukdumboobumm** [comment]
Just throwing this out there in case it sparks any aha-moments: I'm running on a raspberry pi 4 with up-to-date Buster, and I can confirm that **every time** my sensors stop working my wifi also cuts out. The wifi is a known issue in the kernel, see (https://github.com/raspberrypi/firmware/issues/1196) This affects 3 of the Pi's I'm running at home (but not all of them). 

I can't say yet for certain that the issue are related. I'll keep trying to break things and report back with any new information.

**Comment by javand** [comment]
Update: Even though I updated to the latest Ubuntu kernel I still experienced the issue of the usb disconnects via ohci drivers. Since I'm running this in a VM I then installed new usb card to attempt run the wyze hub via Ubuntu's usb 3 xhci drivers. I can report this has been stable for 5 days now, where as in the past it would barely make it past 24hrs - if you can use xhci drivers I would attempt doing so.

**Comment by gterpstra75** [comment]
I have been having what sounds like the same problem for several months now.  My wyze sensors stop reporting usually within 24-hrs but sometimes they will last for a few days after a reboot.   A reboot will always fix the problem.   When my wyze sensors stop working, the wyse hub still has a blue light.    I am running HA in docker on a ubuntu-18.04 LTS machine.

@javand, did ubuntu's usb 3 xhci drives fix your issue?

**Comment by bschatzow** [comment]
I am in the process of moving from a Pi to a windows VM.  I do I configure the USB on the windows machine to look the same to this sensor?

**Comment by javand** [comment]
@gterpstra75 yes I had the same symptoms. I moved the hub to a USB 3 port and used the xhci drivers. It's been running great for over a week now.

**Comment by peterpme** [comment]
Hey @javand I'm running Ubuntu and I have my wyze plugged into a USB3 port. How do I switch to the XHCI drivers? I tried googling around but it doesn't seem as easy as it looks?

Thanks!

**Comment by javand** [comment]
@peterpme  I’m using virtualbox so it’s just a simple setting: https://www.virtualbox.org/manual/ch03.html#settings-usb

**Comment by gterpstra75** [comment]
Thanks @javand for the information.    I am running hass.io in docker under ubuntu 18.04 LTS machine.   I just installed an UBS 3.0 pci card in the base machine.    Of course, I moved the wyze hub to the card but don't expect any difference.    Once it fails (as I expect anyways) I will reconfigure my setup with virtualbox.   Thanks for your help.

**Comment by RonSpawnson** [comment]
Also having this issue :(

**Comment by gterpstra75** [comment]
Update:   I did try virtualbox running under ubuntu 18.04 LTS machine.   I tried all 3 USB drivers (OHCI, EHCI & xHCI).   I actually had a faster failure rate with this setup.    I am currently running with the following setup:
Docker under ubuntu 19.10 machine
USB 3.0 PCI card with power connected.

So far after 4 days, I haven't had any failures.   But actually, it is still a little too early to tell because I have rebooted HA a couple of times to install updates over the past four days.   But, this has been so far the most reliable setup for me.    I need WyzeSense to work because I have 10 door and 15 motion sensors.

**Comment by drewh1991** [comment]
@javand thanks for the tip, switching to XHCI seems to have resolved the issue for me as well. Currently running for a few days without disconnects. I'll report back if this doesn't do the trick.

**Comment by hack2spider** [comment]
I thought I`m the only one I think I spent 5 days trouble shooting this ... 

I`m running my hassio under poxmox and I can`t seem to pass-through the USB anymore this was after 0.109.2 update ? 

the proxmox setup is as follows 👍 

root@pve:~# lusb
-bash: lusb: command not found
root@pve:~# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 8087:0a2b Intel Corp. 
Bus 001 Device 004: ID 1a86:e024 QinHeng Electronics 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@pve:~# dmesg | grep hidraw
[    1.711037] hidraw: raw HID events driver (C) Jiri Kosina
[    1.712287] hid-generic 0003:1A86:E024.0001: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[   13.634923] hid-generic 0003:1A86:E024.0002: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[   17.947228] hid-generic 0003:1A86:E024.0003: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[   18.522724] hid-generic 0003:1A86:E024.0004: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[   19.482384] hid-generic 0003:1A86:E024.0005: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[   20.223582] hid-generic 0003:1A86:E024.0006: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[   22.335565] hid-generic 0003:1A86:E024.0007: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257259.345169] hid-generic 0003:1A86:E024.0008: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257259.896521] hid-generic 0003:1A86:E024.0009: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257260.748569] hid-generic 0003:1A86:E024.000A: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257261.853362] hid-generic 0003:1A86:E024.000B: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257262.728236] hid-generic 0003:1A86:E024.000C: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257267.860145] hid-generic 0003:1A86:E024.000D: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257268.437071] hid-generic 0003:1A86:E024.000E: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257269.383774] hid-generic 0003:1A86:E024.000F: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257270.128906] hid-generic 0003:1A86:E024.0010: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257272.248621] hid-generic 0003:1A86:E024.0011: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257444.330744] hid-generic 0003:1A86:E024.0012: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257444.883025] hid-generic 0003:1A86:E024.0013: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257445.734927] hid-generic 0003:1A86:E024.0014: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257446.838821] hid-generic 0003:1A86:E024.0015: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257447.713816] hid-generic 0003:1A86:E024.0016: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257452.842635] hid-generic 0003:1A86:E024.0017: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257453.418912] hid-generic 0003:1A86:E024.0018: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257454.365397] hid-generic 0003:1A86:E024.0019: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257455.109833] hid-generic 0003:1A86:E024.001A: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[257457.222442] hid-generic 0003:1A86:E024.001B: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[258088.008143] hid-generic 0003:1A86:E024.001C: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[258092.134055] hid-generic 0003:1A86:E024.001D: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[258555.685770] hid-generic 0003:1A86:E024.001E: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[258556.237786] hid-generic 0003:1A86:E024.001F: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[258557.097555] hid-generic 0003:1A86:E024.0020: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[258558.205953] hid-generic 0003:1A86:E024.0021: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[258559.081580] hid-generic 0003:1A86:E024.0022: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[258564.217883] hid-generic 0003:1A86:E024.0023: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[258564.793495] hid-generic 0003:1A86:E024.0024: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[258565.736281] hid-generic 0003:1A86:E024.0025: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[258566.477995] hid-generic 0003:1A86:E024.0026: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
[258568.589370] hid-generic 0003:1A86:E024.0027: hiddev0,hidraw0: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:14.0-1/input0
root@pve:~# qm set 100 -usb2 host=1a86:e024
update VM 100: -usb2 host=1a86:e024
root@pve:~# cat /etc/pve/qemu-server/100.conf | grep usb
usb0: host=1a86:e024
usb1: host=1a86:e024
usb2: host=1a86:e024
root@pve:~#

home assistant VM 100 shows the following : 

➜  /workspace lsusb                        
zsh: corrupt history file /root/.zsh_history
➜  /workspace lsusb
Bus 005 Device 001: ID 1d6b:0001
Bus 003 Device 001: ID 1d6b:0001
Bus 002 Device 002: ID 0627:0001
Bus 001 Device 001: ID 1d6b:0002
Bus 003 Device 003: ID 1a86:e024
Bus 004 Device 001: ID 1d6b:0001
Bus 002 Device 001: ID 1d6b:0001
Bus 003 Device 002: ID 1a86:e024
➜  /workspace dmesg | grep hidraw
[    1.745842] hidraw: raw HID events driver (C) Jiri Kosina
[    2.683429] hid-generic 0003:0627:0001.0001: input,hidraw0: USB HID v0.01 Mouse [QEMU QEMU USB Tablet] on usb-0000:00:01.2-1/input0
[    3.157849] hid-generic 0003:1A86:E024.0002: hiddev96,hidraw1: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:1d.0-1/input0
➜  /workspace 

so home assistant config should look for hidraw1 which I have set but **no luck** ...

any help appreciated.

**Comment by 1337derpdaderp** [comment]
I am also having this problem. I've had it for a variety of HA versions, (i should have never upgraded in the begining). Wyze sensors just stop responding on HA side randomly (could be a day or longer sometimes). They still flash red when you walk by them but HA doesn't recognize any change in their status. 

Any update to this? Wishing I just had xiaomi motion sensors. Those seem to be flawless... 

Running HA on raspi4.

**Comment by gterpstra75** [comment]
> I am also having this problem.

Have you upgraded to the latest version?

**Comment by damato300x7** [comment]
I’ve had 0 issues since upgrading 0.0.7

**Comment by 1337derpdaderp** [comment]
> I’ve had 0 issues since upgrading 0.0.7

What HA version?

**Comment by 1337derpdaderp** [comment]
> > I am also having this problem.
> 
> Have you upgraded to the latest version?

for HACS Wyze? yes.

**Comment by bseishen** [comment]
Zero issues with latest 0.0.7 with running it in an unraid docker. It's been stable. One thing that has helped me a lot is creating a udev rule to create a device at /dev/wyzesense

--
Ben S. Eishen
On 5/22/2020 8:23:17 AM, 1337derp <notifications@github.com> wrote:
I am also having this problem.
Have you upgraded to the latest version?
for HACS Wyze? yes.

**Comment by atechnical** [comment]
I am having this issue. I'm running HA on a virtualbox on a windows 10 pc. Everything was working fine until I added 8 more sensors mostly door/window sensors. Now I would have to restart the VM multiple times a day to keep it running.

**Comment by gterpstra75** [comment]
> I am having this issue. I'm running HA on a virtualbox on a windows 10 pc. Everything was working fine until I added 8 more sensors mostly door/window sensors. Now I would have to restart the VM multiple times a day to keep it running.

Which version of Wyzesense are you running?    (0.8?)

**Comment by atechnical** [comment]
Yes version 0.8. I'm not even sure it's the add on, there are threads in
the Wyze forums for the same issue and the users are not using HA. . Thanks

**Comment by gterpstra75** [comment]
> Yes version 0.8. I'm not even sure it's the add on, there are threads in the Wyze forums for the same issue and the users are not using HA. . Thanks

Good.      I know that I have issues for several months with wyzesense stopping to work.   I have 25 motion and 11 door sensors now.   So I need this to work.   I have been running consistently for over a month now w/o any errors.    You may want to look at:

https://github.com/kevinvincent/ha-wyzesense/issues/141#issue-622707767
https://github.com/kevinvincent/ha-wyzesense/issues/114#issuecomment-619629898

There are also comments on virtualbox setup:
I can not find the link now but basically it stated success with using USB 3.0 drivers.    I didn't have success but worth a try.

**Comment by kzaoaai** [comment]
back when I was using virtualbox, switching to usb 1.1 (OHCI) fixed my issues, so you might want to try that if switching to 3.0 doesn't.

**Comment by atechnical** [comment]
Thanks for the replies. I recently upgraded to the latest edition of Virtual Box.not sure the sensors stopped working directly after but I've rolled it back to 6.1.4 along with the corresponding Expansion pack that impacts the USB connections. I'll see if that works and update this thread. 12 hours and it's been fine so far.

**Comment by atechnical** [comment]
Well..it didn't last long. Some sensors would work while others stopped again. I've moved onto changing to USB 3.0 settings as suggested in the comment you suggested.
https://github.com/kevinvincent/ha-wyzesense/issues/20#issuecomment-595829838

**Comment by atechnical** [comment]
This time I set the Virtual Box adapter to 1.0 and notifications worked for the shortest time period yet. I received the following erno110 error this morning when it stopped working. 

 Logger: custom_components.wyzesense.wyzesense_custom
Source: custom_components/wyzesense/wyzesense_custom.py:373
Integration: wyzesense (documentation)
First occurred: 8:51:41 AM (1 occurrences)
Last logged: 8:51:41 AM

[Errno 110] Operation timed out

**Comment by Troublebrewing** [comment]
I think this may be the same as issue #153 and #157 

I am running wyzesense as a component installed via HACS. 
Home Assistant Host OS: HassOS 4.11 (VirtualBox VM on Windows 10 host machine)
HA version: 0.114.2
HACS: 1.3.3
Wyzesense:  0.0.9

Getting nearly the same error in system log as @atechnical 
My logs from 5 minutes leading up to error: https://pastebin.com/TJ1Y6izb

I have tried changing the USB controller in the VM to USB 1.0 and USB 2.0. I can try 3.0 tonight but this doesn't appear to solve the problem.

**Comment by zee-shany** [comment]
> > I have tried changing the USB controller in the VM to USB 1.0 and USB 2.0. I can try 3.0 tonight but this doesn't appear to solve the problem.
> 
> switching to USB 3 resolved my stability issues.

hi, how do you do the switch from USB 2 to 3?

**Comment by zee-shany** [comment]
> > > I have tried changing the USB controller in the VM to USB 1.0 and USB 2.0. I can try 3.0 tonight but this doesn't appear to solve the problem.
> > 
> > 
> > switching to USB 3 resolved my stability issues.
> 
> hi, how do you do the switch from USB 2 to 3?

found it, after installing vb extension pack.
