### ISSUE TITLE
Wyze Sense Dongle Not Recognized

### ISSUE THREAD

**Issue by jbcole05** [kevinvincent/ha-wyzesense#95]
I am running Hassio v0.104.1 on an Intel NUC running Ubuntu Desktop v18.04. Previously I had it running on a RPi where it worked fine, but recently migrated to this new platform. I notice that the light on the dongle does not turn blue, but stays amber. The contents of the log file have been posted to pastebin with the title B Cole - Wyze Sense Dongle Not Recognized.

**Comment by photinus** [comment]
I did a couple searches on paste bin and couldn't find your logs. Can you share a link?

Can you also run this command: 
dmesg | grep hidraw

How are you running Hassio under Ubuntu Desktop? Docker? VM?

**Comment by jbcole05** [comment]
Thanks for your reply. I tried to find it again on pastebin and couldn't. I might have done something wrong when I posted it. Anyway, error log says:

Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 114, in setup_platform
    ws = beginConn()
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-2>", line 2, in beginConn
  File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/config/custom_components/wyzesense/binary_sensor.py", line 112, in beginConn
    return Open(config[CONF_DEVICE], on_event)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 561, in Open
    return Dongle(device, event_handler)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 297, in __init__
    self._Start()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 492, in _Start
    self._Inquiry()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 398, in _Inquiry
    resp = self._DoSimpleCommand(Packet.Inquiry())
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 393, in _DoSimpleCommand
    self._DoCommand(pkt, cmd_handler, timeout)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 379, in _DoCommand
    self._SendPacket(pkt)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 331, in _SendPacket
    pkt.Send(self.__fd)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 106, in Send
    ss = os.write(fd, pkt)
BrokenPipeError: [Errno 32] Broken pipe

I installed it per the directions from Frenck described in https://gist.github.com/frenck/32b4f74919ca6b95b30c66f85976ec58

Thanks, Brad

**Comment by jbcole05** [comment]
These directories don't exist in my installation:

/usr/src/homeassistant
/usr/local/lib/python3.7
/config

I need to point these to the correct path, but not sure how.

**Comment by jbcole05** [comment]
dmesg | grep hidraw

[    1.632497] hidraw: raw HID events driver (C) Jiri Kosina
[    7.850852] hid-generic 0003:046D:C52B.0001: input,hidraw0: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-0000:00:15.0-4/input0
[    7.911054] hid-generic 0003:046D:C52B.0002: input,hiddev0,hidraw1: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-0000:00:15.0-4/input1
[    7.911523] hid-generic 0003:046D:C52B.0003: hiddev1,hidraw2: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:00:15.0-4/input2
[    8.055175] logitech-djreceiver 0003:046D:C52B.0003: hiddev0,hidraw0: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:00:15.0-4/input2
[    8.179778] hid-generic 0003:046D:404B.0004: input,hidraw1: USB HID v1.11 Keyboard [Logitech Unifying Device. Wireless PID:404b] on usb-0000:00:15.0-4/input2:1
[    8.329446] logitech-hidpp-device 0003:046D:404B.0004: input,hidraw1: USB HID v1.11 Keyboard [Logitech K400] on usb-0000:00:15.0-4/input2:1
[ 4581.176714] hid-generic 0003:1A86:E024.0005: hiddev1,hidraw2: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:15.0-1/input0
[ 4623.444565] hid-generic 0003:1A86:E024.0006: hiddev1,hidraw2: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:15.0-2/input0
[ 4652.373046] hid-generic 0003:1A86:E024.0007: hiddev1,hidraw2: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:15.0-1/input0
[ 5025.539603] hid-generic 0003:1A86:E024.0008: hiddev1,hidraw2: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:15.0-1/input0
[36280.141402] hid-generic 0003:1A86:E024.0009: hiddev1,hidraw2: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:15.0-1/input0
[39309.006657] hid-generic 0003:1A86:E024.000A: hiddev1,hidraw2: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:00:15.0-1/input0

**Comment by photinus** [comment]
What does your config entry look like?

**Comment by jbcole05** [comment]
Well, I had device: "hidraw0" so I changed it to device: auto. After making that change the blue light on the dongle came on. HA still didn't recognize any of the sensors, so I had to scan and install each of them again. Bottom line, though, is that I am back in business. Thanks very much for pointing me in the right direction!
